import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generatePDFReport = (transactions, summary, dateRangeStr, profile) => {
  const doc = new jsPDF('p', 'pt', 'a4');

  // Colors
  const brandColor = [0, 113, 227]; // #0071e3
  const successColor = [52, 199, 89];
  const dangerColor = [255, 69, 58];
  const textColor = [29, 29, 31];
  const textSecondary = [134, 134, 139];

  // --- HEADER ---
  doc.setFillColor(...brandColor);
  doc.rect(0, 0, 595.28, 100, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(26);
  doc.setFont('helvetica', 'bold');
  doc.text('AVORA', 40, 45);
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('Premium Financial Report', 40, 65);
  
  doc.setFontSize(12);
  doc.text(`Generated for: ${profile?.name || 'Avora User'}`, 350, 45);
  doc.text(`Date Range: ${dateRangeStr}`, 350, 65);

  // --- SUMMARY SECTION ---
  doc.setTextColor(...textColor);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Financial Summary', 40, 140);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  
  // Income
  doc.setTextColor(...successColor);
  doc.text(`Total Income: + Rs. ${summary.income.toLocaleString()}`, 40, 165);
  // Expense
  doc.setTextColor(...dangerColor);
  doc.text(`Total Expense: - Rs. ${summary.expense.toLocaleString()}`, 250, 165);
  
  // Net
  doc.setTextColor(...textColor);
  doc.setFont('helvetica', 'bold');
  doc.text(`Net Balance: Rs. ${summary.net.toLocaleString()}`, 40, 190);

  // --- TRANSACTIONS TABLE ---
  const tableData = transactions.map(tx => {
    return [
      new Date(tx.date).toLocaleDateString('en-GB'),
      tx.type.toUpperCase(),
      tx.categoryName || 'General',
      tx.note || '-',
      `${tx.type === 'expense' ? '-' : '+'} Rs. ${Number(tx.amount).toLocaleString()}`
    ];
  });

  doc.autoTable({
    startY: 230,
    head: [['Date', 'Type', 'Category', 'Note', 'Amount']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: brandColor, textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [245, 245, 247] },
    bodyStyles: { textColor: textColor },
    columnStyles: {
      4: { halign: 'right', fontStyle: 'bold' }
    },
    didParseCell: function (data) {
      if (data.section === 'body' && data.column.index === 4) {
        if (data.cell.raw.includes('-')) {
          data.cell.styles.textColor = dangerColor;
        } else if (data.cell.raw.includes('+')) {
          data.cell.styles.textColor = successColor;
        }
      }
    },
    margin: { top: 120, bottom: 50 },
    didDrawPage: function (data) {
      // Footer
      const str = 'Page ' + doc.internal.getNumberOfPages();
      doc.setFontSize(10);
      doc.setTextColor(...textSecondary);
      doc.text(str, data.settings.margin.left, doc.internal.pageSize.height - 30);
      doc.text('Generated by Avora', doc.internal.pageSize.width - 150, doc.internal.pageSize.height - 30);
    }
  });

  doc.save(`Avora_Report_${new Date().getTime()}.pdf`);
};
